### ISSUE TITLE
`getCountryCode` internal function fail with `ja` locale

### ISSUE THREAD

**Issue by mathix420** [tadeegan/locale-currency#10]
The `ja` locale should return same result as `ja-JP`.

Currently `getCountryCode` will return `JA` but `JP` is the expected result.

There might be a lot of exceptions like this one, maybe you can use an underlying library for that.

**Comment by tadeegan** [comment]
What is the failure at the public api level? `localeCurrency.getCurrency('ja-JP') == 'JPY'` Seems to work okay?

**Comment by mathix420** [comment]
`localeCurrency.getCurrency('ja') == null` should return `'JPY'`

**Comment by tadeegan** [comment]
ja is the language not the locale. I don't think ja alone is a valid i18n country code.
