### ISSUE TITLE
accidental global

### ISSUE THREAD

**Issue by kumavis** [tadeegan/locale-currency#3]
https://github.com/tadeegan/locale-currency/blob/master/index.js#L26

**Comment by tadeegan** [comment]
Would this fix your issue? https://github.com/tadeegan/locale-currency/pull/4

**Comment by kumavis** [comment]
@tadeegan yep thanks, sorry for the low-effort drive-by issue (I was filing a number of those that day)

**Comment by jaydenseric** [comment]
Looks like this has been fixed, and can be closed?
